//
//  Locations.swift
//  Berliners
//
//  Created by Martijn van Gogh on 08-03-16.
//  Copyright © 2016 Martijn van Gogh. All rights reserved.
//

import Foundation
import MapKit

struct Locations {
    static let pinTitle: [String] = [
        "Camp Nou",
        "Casa Batllo",
        "Colonia Guëll",
        "Picasso museum",
        "Sitges",
        "Café Cometa",
        "Café Federal",
        "Casa Vicens",
        "Torre de Bellesguard",
        "Casa Amatller",
        "Hospital de sant Pau",
        "Park Guëll",
        "Casa Mila",
        "Bar Marsella",
        "Bar London",
        "La Cambicha",
        "La Bella Napoli",
        "Bar Electricitat",
        "Bar La Plata",
        "Blai 9",
        "Blai Tonight",
        "Taca de Cafe",
        "Cal Boter",
        "Platja de Bogatel",
        "Font Magica/Montjuïc",
        "Restaurant Mirablau",
        "Mercat de Santa Caterina",
        "Bar Absenta",
        "Antic Teatre",
        "Mercat dels Encants Vells",
        "Salt Beachclub",
        "La Caseta del Migdia",
        "La Esquinica",
        "La Flauta",
        "El Velodromo",
        "Koska",
        "La Tasqueta de Blai",
        "Bodega d’en Rafael",
        "Celler Cal Marino",
        "Bodega Biarritz 1881",
        "Petit Pau Restaurant",
        "Felice",
        "L’Ovella Negra",
        "Cervecería El Agüelo",
        "Sor Rita Bar",
        "El Cangrejo",
        "Rubi Bar",
        "Manchester Bar",
        "Hardlopen met de Barcelonezen",
        "Cava Bar",
        "Taktika Berri",
        "Jai-Ca",
        "Tapas 24",
        "El Sortidor",
        "Taverna Can Margarit",
        "Sol Soler",
        "La Pepa",
        "La Taverna del Clínic",
        "Heliogabal",
        "El Collectionista",
        "El Colmado",
        "Sidecar",
        "Jamboree",
        "Cat Bar",
        "Ale & Hop",
        "Sagrada Familia"]
    
    static let pinLocation: [String] = [
            "C. Aristides Maillol, 12",
            "Passeig de Gràcia, 43",
            "Calle Claudi Güell, 08690",
            "Carrer Montcada, 15-23",
            "",
            "Carrel del Parlament 20",
            "Carrer del Parlament 39",
            "Carrer de les Carolines, 18-24",
            "Carrer de Bellesguard, 16",
            "Passeig de Gràcia, 41",
            "Carrer de Sant Antoni Maria Claret, 171",
            "Carrer d'Olot",
            "Provença, 261-265",
            "Carrer Sant Pau, 65",
            "Carrer Nou de la Rambla, 34",
            "Carrer Poeta Cabanyes, 43",
            "Carrer de Margarit, 12-14",
            "Carrer de Sant Carles, 15",
            "Carrer de la Mercè, 28",
            "Carrer de Blai, 9",
            "Carrer de Blai, 23",
            "Carrer de la Riera de Sant Miquel, 77",
            "Carrer de Tordera, 62",
            "Paseo Maritimo del Bogatell, 80",
            "Plaça de Carles Buïgas, 1",
            "Plaça Doctor Andreu",
            "Av. de Francesc Cambó, 16",
            "Carrer de Sant Carles, 36",
            "Carrer de Verdaguer i Callís, 12",
            "Calle Castillejos, 158",
            "Passeig Mare Nostrum, 19-21",
            "Mirador del Migdia (op het Montjuïc-berg)",
            "Passeig de Fabra i Puig, 296",
            "Carrer Aribau, 23",
            "Carrer Muntaner, 213",
            "Carrer de Blai, 8",
            "Carrer Blai, 17",
            "Carrer de Manso, 52",
            "Carrer de Margarit, 52",
            "Calle Vidre, 8",
            "Carrer de l'Espanya Industrial num. 22",
            "Calle Francisco Giner 22",
            "Carrer de les Sitges, 5",
            "Carrer d’Avinyó, 37",
            "Carrer de la Mercè, 27",
            "Carrer de Montserrat, 9",
            "Carrer dels Banys Vells, 6",
            "Carrer Milans, 5",
            "Carretera de les Aigües //bb",
            "Carrer de la Reina Cristina, 7",
            "Valencia 169",
            "Carrer de Ginebra 13",
            "Carrer de Diputació 24",
            "Plaça Sortidor",
            "Carrer de la Concòrdia 21",
            "Plaça del Sol 21-22",
            "Ronda de sant pau 7",
            "Rosselló, 155",
            "Carrer Ramón y Cajal 80",
            "Torrent de les Flors 46",
            "C/ de la Cera 35",
            "Plaza Reial 7",
            "Plaça Reial 18",
            "Carrer Boria 17",
            "Carrer Basses de Sant Pere 10",
            "Carrer de Mallorca"]
    
    static let pinDescription: [String] = [
    "De officiële naam van het stadion was van de opening tot 2000 Nou Estadi del Futbol Club Barcelona. De naam Camp Nou, Catalaans voor nieuw veld, werd echter vanaf de opening al gebruikt als bijnaam en het werd in 2000 na een stemming onder de socios (clubleden) aangenomen als officiële naam.",
    "Casa Batlló, gelegen aan de Passeig de Gràcia in Barcelona is een schepping van de modernistische architect Antoni Gaudí. Het pand werd door hem verbouwd tussen 1904 en 1906 voor de textielmagnaat Josep Batlló i Casanovas. Net als bij het even verderop aan dezelfde straat gelegen Casa Milà is hier niets hoekigs, maar alles is golvend en afgerond net als de golven van de zee.",
    "Cripta Colònia Güell is het enige resultaat dat Antoni Gaudí heeft kunnen bereiken bij de bouw van een kerk in de door Güell bedachte arbeiderswijk Colònia Güell in het dorpje Santa Coloma de Cervelló. Hoe de voltooide kerk eruit zou gaan zien is slechts op enkele vage schetsen te zien. Duidelijke tekeningen ontbreken - zo kenmerkend voor Gaudí's manier van werken.",
    "Met meer dan 4250 werken heeft het Picasso Museum in Barcelona de meest uitgebreide collectie van alle Picasso musea. Vooral zijn beginperiode (1891-1905) is goed vertegenwoordigd. Uitblinker in de collectie is Picasso´s interpretatie van Velazquez´ Las Meninas. Zondag na 15 uur gratis entree.",
    "Erkend als een van de meest charmante steden aan de Catalaanse kust met een mild en gematigd microklimaat, wat betekent dat bezoekers elke maand van het jaar van benijdenswaardige temperaturen kunnen genieten. Op 35 km van Barcelona bij uitstek een plaats voor de locals.",
    "Ver van de massa toerisme en vooral door locals bezocht, is deze straat een waar foodie paradijs voor iedereen wie van lekker eten houdt. Dat Cometa hier ligt is dus al een goed teken!",
    "Vernoemd naar een klein dorpje in New South Wales in Australië, breng je in dit charmante caféetje in Barcelona de eerste uren van je dag door. De relaxte vibe nodigt menig koffieliefhebber uit om een paar uur te blijven hangen, al dan niet over het prachtige dakterras te lopen om te genieten van de zonnetje. In het weekend kan het nogal druk zijn, maar doordeweeks is het goed te doen. Maar al ben je er op zaterdag en moet je lang wachten, trust us: het is het wachten waard!",
    "Casa Vicens in Barcelona (Spanje) was het eerste belangrijke bouwwerk van de architect Antoni Gaudí en behoort tot het Modernisme Català, de Catalaanse variant van de art nouveau- en jugendstilbeweging. In 2005 werd het, samen met andere werken van Gaudí, door UNESCO op de Werelderfgoedlijst geplaatst.",
    "Het herenhuis Bellesguard, ook wel Casa Figueras genoemd, werd gebouwd tussen 1900 en 1909 aan de Carrer de Bellesguard 16-20 in Barcelona voor Doña María Sagués (de weduwe van Figueras)[1] volgens ontwerpen van de Spaans/Catalaanse architect Antoni Gaudí.",
    "Vlak naast het Casa Batlló, op de Passeig de Gràcia, staat het prachtige Casa Amatller. Dit huis is het zoveelste pareltje van modernistische architectuur in Barcelona. Het is géén realisatie van Antoni Gaudí maar van een andere belangrijke architect van het Catalaanse modernisme, Josep Puig i Cadafalch.",
    "In 1997 werd het Hospital de Sant Pau samen met Palau de la Música Catalana door UNESCO op de Werelderfgoedlijst geplaatst. Toch doet dit gebouwenstelsel nog gewoon dienst als ziekenhuis. Gaudi zelf is hier overleden in 1926 nadat hij door de tram was aangereden.",
    "Park Güell is een gestrekt stadspark in Barcelona, in het Spaanse landsdeel Catalonië. Het is gelegen in het stadsdeel Gràcia in het noordoosten met een oppervlakte van 15 ha met dichte pijnbossen, lanen met palmen en een door bomen omzoomd plein. Een bonte bank (een reuzenslang) kronkelt door het park (het aards paradijs) als rendez-vousplaats (de appel).",
    "Casa Milà (1906-1910) is een appartementengebouw van architect Antoni Gaudí en het is een van zijn bekendste werken. Het gebouw werd opgetrokken onder het mecenaat van de adellijke familie Milà. Casa Milà ligt aan de Passeig de Gràcia (Paseo de Grácia) in Barcelona. De buitenmuren zijn golvend uitgevoerd.",
    "Bar Marsella is volgens mensen de oudste bar van Barcelona, en dat zie je natuurlijk ook aan alles terug. De favoriete plek van onder meer Gaudí, Hemingway, Picasso en Dalí. De bar bestaat al sinds 1820 en staat vooral bekend om zijn absint likeur. Deze bar is alleen in de nacht geopend. Leuk detail: de film Vicky Cristina Barcelona werd hier opgenomen.",
    "London Bar bestaat sinds 1910 en is sindsdien een icoon voor muziekliefhebbers en een bedevaartsoord voor veel schrijvers. De bar werd vaak bezocht door mensen uit de theaterwereld. Acteurs, agenten, intellectuelen en kunstenaars zoals Dalí, Picasso en de oprichters en componenten van Circus Raluy waren hier ook van de partij. Met zijn marmeren tafels en modernistische decor, lijkt London Bar een filmset en bruist van het leven.",
    "Calle Blai: “Prachtig straatje vol met bars en vol met mensen. Het ademt gezelligheid. Je kan hier tapas nemen, een biertje drinken, wat uitgebreider avondeten. Alles betaalbaar. In de zijstraatjes van Calle Blai zitten ook nog twee leuke plaatsen om te eten: La Cambicha (Carrer Poeta Cabanyes, 43) en La Bella Napoli (Carrer de Margarit, 12-14).",
    "Calle Blai: “Prachtig straatje vol met bars en vol met mensen. Het ademt gezelligheid. Je kan hier tapas nemen, een biertje drinken, wat uitgebreider avondeten. Alles betaalbaar. In de zijstraatjes van Calle Blai zitten ook nog twee leuke plaatsen om te eten: La Cambicha (Carrer Poeta Cabanyes, 43) en La Bella Napoli (Carrer de Margarit, 12-14).",
    "Deze ouderwetse bodega stamt uit 1908 en heeft sindsdien vissers en havenarbeiders van het gebied verzorgd met vermuts en gerechten met kokkels en gezouten vlees. Een bar waar vooral veel locals komen en volgens zeggen het menu zingend door de ober aan je wordt voorgedragen!.",
    "In deze typische Catalaanse bar serveren ze alleen eenvoudig eten; brood met tomaat, gefrituurde sardientjes, ansjovis op brood of met salade en de klassieke worst butifarra. Tevens wordt hier nog uit de perron gedronken. De klassieke boerenkaraf die je niet in een glas schenkt, maar waar je direct uit drinkt.",
    "Carrer de Blai: “Onder de lokals een bekende straat. Carrer de Blai is de straat als je pinxtos wil eten. Gelegen in Poble Sec is dit echt een familiebuurt waar weinig toeristen komen. Pinxtos voor een euro en een biertje voor anderhalf is niet iets waar je als Nederlander nee tegen zegt. Probeer vooral Blai Tonight, Quimet & Quimet (geen pinxtos, maar wel top) en bijvoorbeeld Blai 9.",
    "Carrer de Blai: “Onder de lokals een bekende straat. Carrer de Blai is de straat als je pinxtos wil eten. Gelegen in Poble Sec is dit echt een familiebuurt waar weinig toeristen komen. Pinxtos voor een euro en een biertje voor anderhalf is niet iets waar je als Nederlander nee tegen zegt. Probeer vooral Blai Tonight, Quimet & Quimet (geen pinxtos, maar wel top) en bijvoorbeeld Blai 9.",
    "De wijk Garcia heeft gezellige pleintjes met terrassen, originele winkeltjes en boetieken en je kan er even ontsnappen aan de drukte van de binnenstad. En je kunt hier lekker eten, bijvoorbeeld een homemade 3-gangenmenu voor 10 euro bij Taca de Cafe (Carrer de la Riera de Sant Miquel, 77), of authentieke Catalaanse gerechten bij Cal Boter (Carrer de Tordera, 62).",
    "De wijk Garcia heeft gezellige pleintjes met terrassen, originele winkeltjes en boetieken en je kan er even ontsnappen aan de drukte van de binnenstad. En je kunt hier lekker eten, bijvoorbeeld een homemade 3-gangenmenu voor 10 euro bij Taca de Cafe (Carrer de la Riera de Sant Miquel, 77), of authentieke Catalaanse gerechten bij Cal Boter (Carrer de Tordera, 62).",
    "Playa Bogatell is mijn favoriete strand om te relaxen. Minder druk als bij Barceloneta en tevens met gezellige chiringuitos. Meer locals en makkelijk te bereiken met de fiets.",
    "’s avonds is de hele gebied van de Fira tot aan het Palau Nacional verlicht door een water, licht- en muziek show dat plaatsvind op de Font Màgica. Van 1 april t/m 28 mei: vrijdag en zaterdag van 21:00 t/m 22:30 uur. Er is iedere 30 minuten een show. Deze begint om 21:00, 21:30 en 22:00 uur.",
    "Restaurant Mirablau helemaal aan de rand van Barcelona, hoog tegen de berg. Het restaurant zelf is eigenlijk zeer eenvoudig, maar de uitzichten over de stad zijn werkelijk waar adembenemend! Bovendien kan je in die omgeving heerlijk wandelen, want de bossen beginnen voor de deur van Mirablau.",
    "Een overdekte markt in Gaudistijl waar vooral veel verschillend eten/tapas te krijgen is. De markt ligt in het oude Barcelona",
    "Absenta is een bar in Barceloneta (Carrer de Sant Carles, 36), een paar straatjes van mijn huis. Er heerst een belle époque sfeer die ik fantastisch vind en die nog eens versterkt wordt door dat gelijknamige drankje, absinth.",
    "Antic Teatre (Carrer de Verdaguer i Callís, 12) is een beetje verstopte binnentuin vlakbij het muziekpaleis. Vooral lekker in het vroege voorjaar, als het nog wat minder druk is. In de zon, uit de wind!",
    "Op wat het oudste en zeker de grootste openlucht rommelmarkt van Barcelona was, ligt nu een hypermoderne koepel dat de markt overdekt en een moderne uitstraling geeft. Dit is een plek dat de moeite waard is om te zien, niet alleen door alle kraampjes, maar ook door zijn architectonische waarde.",
    "De nieuwe Salt Beachclub, naast het Hotel W,  heeft een geweldig terras aan het strand waar je van lekkere (redelijk dure) cocktails, gourmet burgers en andere lekkernijen kunt genieten. Ideaal om het echte zomerse gevoel te krijgen. Met regelmatige optredens van verschillende DJ’s.",
    "Een nog vrij onbekend terras op de Montjuïc-berg is La Caseta del Migdia. Deze vrij eenvoudige bar van La Caseta is wellicht een groot contrast met de luxe van de andere terrassen hierboven, maar het is desalniettemin een magische plek waar alleen de locals heengaan. Men zegt dat je hier de allerbeste zonsondergang van de stad kunt zien. Er is altijd muziek van woensdag t/m zondag.",
    "Echte Spaanse tapas eten tussen de locals doe je bij een van de onderstaande adressen! Mijn absolute aanraders: Bar Velódromo, La Esquinica en La Flauta.",
    "Echte Spaanse tapas eten tussen de locals doe je bij een van de onderstaande adressen! Mijn absolute aanraders: Bar Velódromo, La Esquinica en La Flauta.",
    "Echte Spaanse tapas eten tussen de locals doe je bij een van de onderstaande adressen! Mijn absolute aanraders: Bar Velódromo, La Esquinica en La Flauta.",
    "Pinchos (of pintxos) komen oorspronkelijk uit het noorden van Spanje en kunnen gezien worden als een soort van tapas. De basis van een pincho is echter altijd hetzelfde. Een schuin afgesneden stuk stokbrood rijk belegd met verschillende ingrediënten. In de vele bars in Carrer de Blai vind je schalen vol met pinchos die op de bar staan.",
    "In de meeste barretjes in Carrer de Blai betaal je één euro per pincho. In iedere pincho is een prikker gestoken die je moet bewaren. Deze worden bij vertrek geteld en hierdoor weet de bediening – en jij – precies hoeveel je moet betalen.",
    "Ouderwetse bodegas of wijnbars waar wijn nog uit grote vaten getapt wordt bestaan nog in Barcelona. Een aanrader als je helemaal tussen de locals wilt zitten.",
    "Vaak bestaat een bodega uit een wijnkelder en een bar, maar je kunt er vaak ook heerlijk tapas eten!",
    "Weer een bodega waar eten en drinken allebei uitmuntend verzorgd is. Deze bodega staat op no. 6 als beste restaurant van Barcelona (van 6000 + restaurants)",
    "Zeer conviviaal restaurant in volkse buurt, maar absoluut lekker en met typische ingrediënten. Eénvoudige gerechten maar zeer goed en smaakvol bereid. Vriendelijke en deskundige Bediening door Paul, waardoor men zich direct 'als thuis' voelt. Dit wordt een vast adres bij elk van m'n Barcelona bezoeken !",
    "No. 20 op Tripadvisor, eenvoudig, goedkoop maar zeer goed restaurant!",
    "Wanneer je juist een relaxte avond wilt met vrienden en het niet al te duur wilt maken, dan is de kroeg van l’Ovella Negra een zeer geschikte plek. L’Ovella Negra (‘het zwarte schaap’) met zijn sfeer van een ouderwetse taverne is een klassieker in Barcelona.",
    "Bij de kroeg El Agüelo vind je veel bier en allerlei goedkope drank. Dit is een zeer rustieke kroeg waar jongeren gaan vooral om veel te drinken en gezellig met elkaar praten. Het is hier ook altijd zeer druk en de sfeer is zoals bij l’Ovella Negra als een ouderwetse taverne.",
    "Sor Rita Bar is een extravagante en zeer bijzondere bar, waar je zowel lekkere cocktails als een biertje kunt drinken. De muziekstijl is van de jaren ’80 en ’90, een tikje retro maar wel leuk. De bar is tot aan de plafonds gedecoreerd met fotolijstjes, damesschoenen en zelfs damesondergoed: alles met humor gemaakt voor de non ‘Sor Rita’.",
    "Een klassieker in Barcelona waar je terug naar de jaren 70 en 80 lijkt te gaan. El Cangrejo (‘krab’ in het Nederlands) is een muziek bar die helemaal niet pretentieus is, met een unieke en bijzondere decoratie van allerlei spullen, foto’s en natuurlijk, krabben.",
    "Het is wellicht even zoeken in de steegjes van El Born, maar als je Rubi Bar eenmaal gevonden hebt zal je niet teleurgesteld worden! Bij deze knusse en relaxte bar met rode verlichting kun je drankjes en cocktails bestellen, terwijl je lekker kletst en geniet van je avond.",
    "Voor de liefhebbers van Rock, Punk, New Wave en classic Britpop is de Manchester Bar in de Raval de juiste plek. Eigenlijk hebben ze twee bars, eentje bij Carrer Valldonzella en de andere in Carrer Milans, dus de keuze is aan jou.",
    "De leukste en spectaculairste manier om hard te lopen in Barcelona doen is op de La Carretera de les Aigües, zeg maar De Waterweg.. Doe met hen mee en geniet onderweg van de mooiste uitzichten over de stad!",
    "Een heerlijke cava makerij,  gecombineerd met één van de toprestaurants van Barcelona.Cava en tapas in een kleine zaak die vol met locals. Tip van Mike Shulmeister met lovende recensies op tripadvisor.",
    "Het beste Baskische restaurant van Barcelona. Autentieke pinxtos en tapas, geserveerd in een klein zaakje waar veel locals komen.",
    "Goedkope tapas die favoriet zijn bij de Barcelonezen zelf in de wijk Barceloneta. Hoge waardering op tripadvisor, alhoewel soms wat aanmerkingen op de bediening.",
    "Tapas 24 is de tapasbar van chefkok Carles Abellan, die ooit stage liep bij El Bulli. En dit is zijn eerbetoon aan de Spaanse tapasbar. Niet de meest sfeervolle tent, maar de tapas zijn goed.",
    "Klassieker in de wijk Poble Sec. Tapas, een middagmenu, uitgebreid (en romantisch) dineren of alleen een drankje behoren allemaal tot de mogelijkheden Met terras op het aanpalende plein.",
    "Een oude taverne in Poble Sec. Traditionele gerechten van de Spaanse Middelandse-Zeekust en uit Andalusië voor redelijke prijzen.",
    "De lekkerste kippenpootjes in town. Geen klassieke TL-verlichte bar, maar een gezellige tent met muziek waar je uren kunt zitten.",
    "La Pepa is een tapas restaurant gespecialiseerd in gegrilde gerechten, vlakbij El Molino, de Moulin Rouge van Barcelona.",
    "Een mythische plek voor liefhebbers van goede tapas. Won al drie keer de prijs voor de beste patates bravas van Barcelona, Andere lekkernijen zijn onder meer cannelloni met champignons, risotto met asperges en gegrilde garnalsen., of Palamos. Wel prijzig: tapas vanaf € 5,80.",
    "Twijfel of deze tent met live-muziek nog wel open is.. Zag er wel erg leuk uit, dus mits in de buurt, het bekijken waard.",
    "Bar met live music; van folky jongens en meisje tot jazz.",
    "Arty tent, van poëzievoordrachten tot experimentele muziek.",
    "Een tent die een soort Melkweg van Barcelona is.",
    "Blues en (vooral) Jazz ´s avonds. Na middernacht disco time (één vloer/verdieping jaren 80, de ander ´2013´ (house en aanverwante klanken dus).",
    "Vegetarisch eten en ambachtelijk drinken. Met zeventien Spaanse ambachtelijke bieren.",
    "Een bar met ambachtelijk bier en eerlijke tapas.",
    "Sinds het leggen van de eerste steen in 1882 wordt bijna voortdurend aan de kerk gebouwd.[1] Alleen gedurende de Spaanse Burgeroorlog heeft de bouw enkele jaren stilgelegen. De huidige officiële opleveringsdatum is in 2026. De snelheid waarmee de bouw vordert, is voor een groot deel afhankelijk van de giften die bezoekers binnenbrengen. De bouw duurt inmiddels zo lang, dat reeds voltooide gedeelten inmiddels gerenoveerd moeten worden."]
    
    static let pinImageName: [String] = [ //afbeelding op de pin
            "campnou.jpg",
            "batllo.jpg",
            "coloniaguell.jpg",
            "picasso.jpg",
            "sitges.jpg",
            "cometa.jpg",
            "federal.jpg",
            "vicens.jpg",
            "bellesguard.jpg",
            "Mtller.jpg",
            "hospital.jpg",
            "guell.jpg",
            "mila.jpg",
            "marsella.jpg",
            "london.jpg",
            "cambicha.jpg",
            "napoli.jpg",
            "electricitat.jpg",
            "laplata.jpg",
            "blai9.jpg",
            "blaitonight.jpg",
            "cafe.jpg",
            "calboter.jpg",
            "bogatel.jpg",
            "magica.jpg",
            "mirablau.jpg",
            "caterinamarkt.jpg",
            "absent.jpg",
            "teatre.jpg",
            "encants.jpg",
            "salt.jpg",
            "caseta.jpg",
            "esquinaca.jpg",
            "flauta.jpg",
            "velodromo.jpg",
            "koska.jpg",
            "tasqueta.jp",
            "rafel.jpg",
            "cal.jpg",
            "biarritz.jpg",
            "pau.jpg",
            "felice.jpg",
            "ovella.jpg",
            "aguelo.jpg",
            "rita.jpg",
            "cangrejo.jpg",
            "rubi.jpg",
            "manchester.jpg",
            "runner.jpg",
            "cavabar.jpg",
            "takitta.jpg",
            "jaica.jpg",
            "tapas24.jpg",
            "sortidor.jpg",
            "margarit.jpg",
            "solsoler.png",
            "lapepa.jpg",
            "tavernaclinic.jpg",
            "heliogabal.jpg",
            "coleccionista.jpg",
            "colmado.jpg",
            "sidecar.jpg",
            "jamboree.jpg",
            "catbar.jpg",
            "alehop.jpg",
            "sagrada.jpg"]
    static let discipline: [String] = [ //Kies uit Strand, Dansen, Berger .. Bepaalt de afbeelding van de pin.
        "Doen",
        "Doen",
        "Doen",
        "Doen",
        "Chillen",
        "Eten",
        "Chillen",
        "Doen",
        "Doen",
        "Doen",
        "Doen",
        "Doen",
        "Doen",
        "Drinken",
        "Drinken",
        "Eten",
        "Eten",
        "Eten",
        "Drinken",
        "Drinken",
        "Drinken",
        "Eten",
        "Eten",
        "Chillen",
        "Doen",
        "Eten",
        "Doen",
        "Drinken",
        "Chillen",
        "Doen",
        "Chillen",
        "Chillen",
        "Eten",
        "Eten",
        "Eten",
        "Eten",
        "Eten",
        "Drinken",
        "Drinken",
        "Drinken",
        "Eten",
        "Eten",
        "Drinken",
        "Drinken",
        "Drinken",
        "Drinken",
        "Drinken",
        "Drinken",
        "Doen",
        "Eten",
        "Eten",
        "Eten",
        "Eten",
        "Eten",
        "Eten",
        "Eten",
        "Eten",
        "Eten",
        "Drinken",
        "Drinken",
        "Drinken",
        "Drinken",
        "Drinken",
        "Drinken",
        "Drinken",
        "Doen"]
    static let latitude: [CLLocationDegrees] = [
        41.380908,
        41.391665,
        41.363866,
        41.385216,
        41.234837,
        41.375867,
        41.376804,
        41.403500,
        41.409132,
        41.391574,
        41.413669,
        41.414387,
        41.395380,
        41.378235,
        41.378076,
        41.373314,
        41.374360,
        41.379368,
        41.380457,
        41.373127,
        41.373576,
        41.398686,
        41.402184,
        41.393818,
        41.371182,
        41.416059,
        41.386369,
        41.379550,
        41.387184,
        41.401016,
        41.369131,
        41.359692,
        41.430512,
        41.386882,
        41.393498,
        41.373156,
        41.373241,
        41.377310,
        41.372495,
        41.380061,
        41.376364,
        41.399209,
        41.384416,
        41.380321,
        41.380945,
        41.377356,
        41.384612,
        41.380695,
        41.406865,
        41.384520,
        41.388450,
        41.381560,
        41.391019,
        41.372505,
        41.373167,
        41.401540,
        41.375553,
        41.388882,
        41.403543,
        41.405926,
        41.394013,
        41.401851,
        41.379732,
        41.384540,
        41.388672,
        41.403694]
    static let longitude: [CLLocationDegrees] = [
        2.122809,
        2.164870,
        2.031858,
        2.180893,
        1.807135,
        2.162007,
        2.162870,
        2.150649,
        2.126626,
        2.165113,
        2.175972,
        2.153505,
        2.161961,
        2.171288,
        2.173072,
        2.165177,
        2.163766,
        2.190079,
        2.180624,
        2.165824,
        2.164722,
        2.154207,
        2.162419,
        2.206431,
        2.151802,
        2.131891,
        2.178157,
        2.191188,
        2.175872,
        2.185960,
        2.190394,
        2.160749,
        2.171047,
        2.161115,
        2.150175,
        2.166029,
        2.165294,
        2.161583,
        2.163103,
        2.175925,
        2.140502,
        2.159241,
        2.169686,
        2.179118,
        2.180925,
        2.174935,
        2.180459,
        2.179178,
        2.109074,
        2.181660,
        2.157531,
        2.187917,
        2.167474,
        2.162157,
        2.160078,
        2.156351,
        2.167005,
        2.151272,
        2.160304,
        2.160561,
        2.169408,
        2.156071,
        2.175265,
        2.178735,
        2.180086,
        2.174367]
    static let url: [String] = [
        ""]
}
